### ISSUE TITLE
Cry function

### ISSUE THREAD

**Issue by nathan-d** [danbosscher/efficiency#2]
Hi, 

Just wondering where the `cry` function is being declared?

Thanks!

**Comment by seeafish** [comment]
To add to that, is `{cry}` a dict with no values?

**Comment by nathan-d** [comment]
Its far more efficient to use the key as the value and negate the need for a value field at all.

**Comment by danbosscher** [comment]
Please do the needful.

**Comment by nathan-d** [comment]
This project is going nowhere.
